/*****************************************************************************
 *  * Project: RooFit                                                           *
 *   *                                                                           *
 *     * This code was autogenerated by RooClassFactory                            *
 *      *****************************************************************************/

#ifndef ROOBIFURSTUDENT
#define ROOBIFURSTUDENT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooBifurStudent : public RooAbsPdf {
	public:
		RooBifurStudent() {} ;
		RooBifurStudent(const char *name, const char *title,
				RooAbsReal& _x,
				RooAbsReal& _m,
				RooAbsReal& _gh,
				RooAbsReal& _gl,
				RooAbsReal& _Nh,
				RooAbsReal& _Nl);
		RooBifurStudent(const RooBifurStudent& other, const char* name=0) ;
		virtual TObject* clone(const char* newname) const { return new RooBifurStudent(*this,newname); }
		inline virtual ~RooBifurStudent() { }

	protected:

		RooRealProxy x ;
		RooRealProxy m ;
		RooRealProxy gl ;
		RooRealProxy gh ;
		RooRealProxy Nl ;
		RooRealProxy Nh ;

		Double_t evaluate() const ;

	private:

		ClassDef(RooBifurStudent,1) // Your description goes here...
};

#endif
