/*****************************************************************************
 *  * Project: RooFit                                                           *
 *   *                                                                           *
 *     * This code was autogenerated by RooClassFactory                            *
 *      *****************************************************************************/

#ifndef ROOSTUDENT
#define ROOSTUDENT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooStudent : public RooAbsPdf {
	public:
		RooStudent() {} ;
		RooStudent(const char *name, const char *title,
				RooAbsReal& _x,
				RooAbsReal& _m,
				RooAbsReal& _g,
				RooAbsReal& _N);
		RooStudent(const RooStudent& other, const char* name=0) ;
		virtual TObject* clone(const char* newname) const { return new RooStudent(*this,newname); }
		inline virtual ~RooStudent() { }

	protected:

		RooRealProxy x ;
		RooRealProxy m ;
		RooRealProxy g ;
		RooRealProxy N ;

		Double_t evaluate() const ;

	private:

		ClassDef(RooStudent,1) // Your description goes here...
};

#endif
